function euler_rates = bh_autogen_euler_rates(theta,psi,p,q,r)
%BH_AUTOGEN_EULER_RATES
%    EULER_RATES = BH_AUTOGEN_EULER_RATES(THETA,PSI,P,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Aug-2020 19:55:47

euler_rates = [(r.*cos(psi)+q.*sin(psi))./cos(theta);q.*cos(psi)-r.*sin(psi);(p.*cos(theta)+r.*cos(psi).*sin(theta)+q.*sin(psi).*sin(theta))./cos(theta)];
